---
- name: Federated SIP setup
  hosts: federated-servers
  vars_files:
    - variables.yml
  sudo: true
  tasks:

    - name: install vim
      yum: name=vim-enhanced

    - name: install epel
      yum: name=epel-release

    - name: install opensips repo
      yum: name=http://yum.opensips.org/2.2/nightly/el/7/x86_64/opensips-yum-nightly-2.2-3.el7.noarch.rpm

    - group: name=opensips state=present
    - user: name=opensips createhome=no group=opensips

    - name: "Install required opensips packages"
      yum: state=present name={{ item }}
      with_items:
        - opensips
        - opensips-db_sqlite
        - opensips-proto_tls
        - opensips-proto_ws
        - opensips-proto_wss
        - opensips-rtpengine
        - opensips-tls_mgm

    - name: install rtpengine deps
      yum: state=present name={{ item }}
      with_items:
        - git
        - gcc
        - make
        - flex
        - bison
        - gettext
        - automake
        - autoconf
        - gdb
        - libtool
        - binutils
        - pkgconfig
        - glib2
        - glib2-devel
        - zlib
        - zlib-devel
        - openssl
        - openssl-devel
        - pcre
        - pcre-devel
        - libcurl
        - libcurl-devel
        - xmlrpc-c
        - xmlrpc-c-devel
        - hiredis
        - hiredis-devel

    - name: install sqlite pcre extension deps
      yum: state=present name={{ item }}
      with_items:
        - sqlite
        - sqlite-devel

    - name: Stopping rtpengine
      service: name=rtpengine state=stopped
      when: firstrun == 'false'
    - name: Stopping opensips
      service: name=opensips state=stopped
      when: firstrun == 'false'

    - git: repo=https://github.com/sipwise/rtpengine.git
       dest=/usr/local/src/rtpengine
       version=mr4.0.1
    - git: repo=https://github.com/ralight/sqlite3-pcre.git
       dest=/usr/local/src/sqlite3-pcre

    - name: Running make for rtpengine
      command: "{{ item }} chdir=/usr/local/src/rtpengine/daemon"
      with_items:
        - make
    - name: Running make install for rtpengine
      command: "cp rtpengine /usr/sbin/rtpengine chdir=/usr/local/src/rtpengine/daemon"

    - name: Running make for sqlite3-pcre
      command: "{{ item }} chdir=/usr/local/src/sqlite3-pcre/"
      with_items:
        - make
    - name: Running make install for sqlite3-pcre
      command: "make install chdir=/usr/local/src/sqlite3-pcre/"

    - name: Copying opensips configuration
      template: src=templates/opensips.cfg.j2 dest=/etc/opensips/opensips.cfg
        mode=0644

    - name: Copying opensips environment files
      copy: src=files/opensips.sysconfig dest=/etc/sysconfig/opensips

    - name: Copying opensips control config
      copy: src=files/opensipsctlrc dest=/etc/opensips/opensipsctlrc

    - name: Copying opensips service script
      copy: src=files/opensips.service dest=/etc/systemd/system/opensips.service

    - name: Copying rtpengine environment files
      template: src=templates/rtpengine.sysconfig.j2 dest=/etc/sysconfig/rtpengine

    - name: Copying rtpengine service script
      copy: src=files/rtpengine.service dest=/etc/systemd/system/rtpengine.service

    - git: repo=https://github.com/OpenSIPS/opensips.git
       dest=/usr/local/src/opensips

    - file: path=/var/db/opensips state=directory mode=0755 group=opensips owner=opensips
    - file: path=/var/db/opensips state=directory mode=0777

    - name: Copying translations table sql create script
      copy: src=files/create_translations_table.sqlite dest=/usr/local/src/create_translations_table.sqlite
    - name: Creating opensips database
      shell: "sqlite3 /var/db/opensips/opensips < /usr/local/src/opensips/scripts/sqlite/standard-create.sql"
      when: firstrun == 'true'
    - name: Creating dialog table
      shell: "sqlite3 /var/db/opensips/opensips < /usr/local/src/opensips/scripts/sqlite/dialog-create.sql"
      when: firstrun == 'true'
    - name: Creating location table
      shell: "sqlite3 /var/db/opensips/opensips < /usr/local/src/opensips/scripts/sqlite/usrloc-create.sql"
      when: firstrun == 'true'
    - name: Creating domain table
      shell: "sqlite3 /var/db/opensips/opensips < /usr/local/src/opensips/scripts/sqlite/domain-create.sql"
      when: firstrun == 'true'
    - name: Creating subscriber table
      shell: "sqlite3 /var/db/opensips/opensips < /usr/local/src/opensips/scripts/sqlite/auth_db-create.sql"
      when: firstrun == 'true'
    - name: Creating translations table
      shell: "sqlite3 /var/db/opensips/opensips < /usr/local/src/create_translations_table.sqlite"
      when: firstrun == 'true'

    - file: path=/var/db/opensips/opensips state=file mode=0777 group=opensips owner=opensips

    - name: Starting rtpengine
      service: name=rtpengine state=started
    - name: Starting opensips
      service: name=opensips state=started
